
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: api-demo_development

test:
  <<: *default
  database: api-demo_test

production:
  <<: *default
  database: api-demo_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['RAILS-4-REST-API-DEMO_DATABASE_PASSWORD'] %>
